### ISSUE TITLE
Alternative APK download?

### ISSUE THREAD

**Issue by IzzySoft** [pskiwi/avr-remote#4]
Would you consider providing the APK outside of Play as well – for those who cannot (eg Huawei devices) or don't want to (privacy folks) use Google? You could e.g. attach it to its corresponding releases, which has become a good practice with many FOSS projects. Thanks in advance!

**Comment by pskiwi** [comment]
Yes, I will try to attach a signed apk to each release.

**Comment by IzzySoft** [comment]
Thanks a lot! Looking forward to that. Once it's there, please let me know here :smiley:

**Comment by pskiwi** [comment]
The APK is available for now:
https://github.com/pskiwi/avr-remote/releases/tag/v1.5.1

**Comment by IzzySoft** [comment]
Thanks a lot! And with the next sync tomorrow, can be installed (and kept up-to-date as long as you keep up attaching the APK to new releases) using the F-Droid client with my repo configured. Should [show up here](https://apt.izzysoft.de/fdroid/index/apk/de.pskiwi.avrremote) in about 23h from now.

(screenshots taken from Play. If you like, I can open a PR with a "starter package" for [Fastlane structures](https://gitlab.com/snippets/1895688) (summary de+en and description en), which you could enhance with screenshots, featureGraphic etc – and also use for deployment to Play (my updater would fetch that automatically as well with new releases). One place to rule them all :wink:
